# Generated by Django 5.1.7 on 2025-03-25 15:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkshopPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', wagtail.fields.StreamField([('section', 15), ('paragraph', 1), ('image', 3), ('embed', 4), ('card_grid', 13), ('card', 11), ('calendly', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 0)]], {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Lees meer', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('image', 7), ('link_text', 8), ('link_page', 9), ('link_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 3), ('embed', 4), ('card', 11), ('card_grid', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 14)]], {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Plak hier je Calendly link, bijvoorbeeld: https://calendly.com/schilderenmetsabine-info/30min'}), 17: ('wagtail.blocks.StructBlock', [[('url', 16)]], {})})),
                ('calendly_embed', models.URLField(blank=True, help_text='Public Calendly embed link of booking page URL (voor iframe)')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
