# Generated by Django 5.1.7 on 2025-03-25 21:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoppage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workshoppage',
            name='start_time',
        ),
        migrations.AddField(
            model_name='workshoppage',
            name='sessions',
            field=wagtail.fields.StreamField([('session', 3)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'Datum van de workshop', 'required': True}), 1: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Starttijd', 'required': True}), 2: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Eindtijd', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('date', 0), ('start_time', 1), ('end_time', 2)]], {})}, verbose_name='Sessies'),
        ),
    ]
