# Generated by Django 5.1.7 on 2025-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshoppage_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='status',
            field=models.CharField(choices=[('open', 'Beschikbaar'), ('full', 'Vol'), ('cancelled', 'Geannuleerd')], default='open', help_text='Geeft aan of deze workshop nog beschikbaar is.', max_length=20, verbose_name='Status van inschrijving'),
        ),
    ]
