# Generated by Django 5.1.7 on 2025-03-26 10:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshoppage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='status_override',
            field=models.CharField(blank=True, help_text="Optioneel: handmatig label voor teasers, bijvoorbeeld 'Nieuw!' of 'Laatste kans'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='sessions',
            field=wagtail.fields.StreamField([('session', 3)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'help_text': 'Datum van de workshop', 'required': True}), 1: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Starttijd', 'required': True}), 2: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Eindtijd', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('date', 0), ('start_time', 1), ('end_time', 2)]], {})}, help_text='Voeg hier de data en tijden van de workshop toe.', verbose_name='Sessies'),
        ),
        migrations.AlterField(
            model_name='workshoppage',
            name='status',
            field=models.CharField(choices=[('open', 'Nog plaatsen beschikbaar'), ('full', 'Volgeboekt'), ('cancelled', 'Geannuleerd')], default='open', help_text='Geeft aan of deze workshop nog beschikbaar is.', max_length=20, verbose_name='Status van inschrijving'),
        ),
    ]
