# Generated by Django 5.1.7 on 2025-05-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('workshops', '0005_alter_workshoppage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoppage',
            name='workshop_image',
            field=models.ForeignKey(blank=True, help_text='Afbeelding voor de workshop kaart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
