# Generated by Django 5.1.7 on 2025-03-25 15:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 15), ('paragraph', 1), ('image', 3), ('embed', 4), ('card_grid', 13), ('card', 11), ('calendly', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 0)]], {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Lees meer', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('image', 7), ('link_text', 8), ('link_page', 9), ('link_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 3), ('embed', 4), ('card', 11), ('card_grid', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 14)]], {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Plak hier je Calendly link, bijvoorbeeld: https://calendly.com/schilderenmetsabine-info/30min'}), 17: ('wagtail.blocks.StructBlock', [[('url', 16)]], {})}),
        ),
    ]
