# Generated by Django 5.1.7 on 2025-04-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='titel van website', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(blank=True, help_text='call to action tekst', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='link naar pagina waar de call to action naartoe gaat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(blank=True, help_text='subtitel van website', max_length=255),
        ),
    ]
