# Generated by Django 5.1.7 on 2025-03-27 13:38

import django.db.models.deletion
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.StreamField([('section', 15), ('paragraph', 1), ('image', 3), ('embed', 4), ('card_grid', 13), ('card', 11), ('calendly', 17), ('workshop_teaser', 21), ('image_scroller', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 0)]], {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Lees meer', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('image', 7), ('link_text', 8), ('link_page', 9), ('link_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 3), ('embed', 4), ('card', 11), ('card_grid', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 14)]], {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Plak hier je Calendly link, bijvoorbeeld: https://calendly.com/schilderenmetsabine-info/30min'}), 17: ('wagtail.blocks.StructBlock', [[('url', 16)]], {}), 18: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['workshops.WorkshopPage']}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "Optioneel: label zoals 'Nieuw', 'Laatste kans', etc.", 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optioneel: afbeelding overschrijven', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('workshop_page', 18), ('custom_label', 19), ('override_image', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Voeg een of meerdere afbeeldingen toe', 'label': 'Afbeeldingen'}), 23: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Schakel aan/uit of gebruikers zelf door afbeeldingen kunnen klikken', 'label': 'Toon navigatieknoppen', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('images', 22), ('show_controls', 23)]], {})})),
                ('thank_you', wagtail.fields.StreamField([('section', 15), ('paragraph', 1), ('image', 3), ('embed', 4), ('card_grid', 13), ('card', 11), ('calendly', 17), ('workshop_teaser', 21), ('image_scroller', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 0)]], {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Lees meer', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('image', 7), ('link_text', 8), ('link_page', 9), ('link_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('cards', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('paragraph', 1), ('image', 3), ('embed', 4), ('card', 11), ('card_grid', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 14)]], {}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Plak hier je Calendly link, bijvoorbeeld: https://calendly.com/schilderenmetsabine-info/30min'}), 17: ('wagtail.blocks.StructBlock', [[('url', 16)]], {}), 18: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['workshops.WorkshopPage']}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': "Optioneel: label zoals 'Nieuw', 'Laatste kans', etc.", 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optioneel: afbeelding overschrijven', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('workshop_page', 18), ('custom_label', 19), ('override_image', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Voeg een of meerdere afbeeldingen toe', 'label': 'Afbeeldingen'}), 23: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Schakel aan/uit of gebruikers zelf door afbeeldingen kunnen klikken', 'label': 'Toon navigatieknoppen', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('images', 22), ('show_controls', 23)]], {})})),
                ('form_fields', wagtail.fields.StreamField([('text', 3), ('email', 3), ('textarea', 3), ('checkbox', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('required', 1), ('help_text', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('label', 0), ('help_text', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
    ]
