# Generated by Django 5.1.7 on 2025-04-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformpage',
            options={'verbose_name': 'Contact Form Page', 'verbose_name_plural': 'Contact Form Pages'},
        ),
    ]
